# Generated by Django 5.0.6 on 2024-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='govenance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
